const books = [
  {
    id: 0,
    title: "El señor de los anillos",
    genre: "Fantasy",
    author: "Tolkien, J.R.R",
    publication: 1954,
    image: "src/images/books/el-señor-de-los-anillos.jpg",
    price: 1234,
  },
  {
    id: 1,
    title: "Harry Potter y la Piedra Filosofal",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1997,
    image: "src/images/books/harry-potter-y-la-pieda-filosofal.jpg",
    price: 1234,
  },
  {
    id: 2,
    title: "Harry Potter y la Camara Secreta",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1954,
    image: "src/images/books/harry-potter-y-la-camara-secreta.png",
    price: 1234,
  },
  {
    id: 3,
    title: "Harry Potter y el Prisionero de Azkaban",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1954,
    image: "src/images/books/harry-potter-y-el-prisionero-de-azkaban.png",
    price: 1234,
  },
  {
    id: 4,
    title: "Harry Potter y el Caliz de Fuego",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1954,
    image: "src/images/books/harry-potter-y-el-caliz-de-fuego.png",
    price: 1234,
  },
  {
    id: 5,
    title: "Harry Potter y la Orden del Fenix",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1954,
    image: "src/images/books/harry-potter-y-la-orden-del-fenix.jpg",
    price: 1234,
  },
  {
    id: 6,
    title: "Harry Potter y el Misterio del Principe",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1954,
    image: "src/images/books/harry-potter-y-el-misterio-del-principe.jpg",
    price: 1234,
  },
  {
    id: 7,
    title: "Harry Potter y las Reliquias de la muerte",
    genre: "Fantasy",
    author: "J.K.Rowling",
    publication: 1954,
    image: "src/images/books/harry-potter-y-las-reloquias-de-la-muerte.jpg",
    price: 1234,
  },
  {
    id: 8,
    title: "Drácula",
    genre: "Terror",
    author: "Bram Stoker",
    publication: 1897,
    image: "src/images/books/dracula.jpg",
    price: 1234,
  },
  {
    id: 9,
    title: "El Exorcista",
    genre: "Terror",
    author: "William Peter Blatty",
    publication: 1971,
    image: "src/images/books/el-exorcista.jpg",
    price: 1234,
  },
  {
    id: 10,
    title: "La Invitada",
    genre: "Terror",
    author: "Jennifer McMahon",
    publication: 2021,
    image: "src/images/books/la-invitada.jpg",
    price: 1234,
  },
  {
    id: 11,
    title: "Frankenstein",
    genre: "Terror",
    author: "Mary Shelley",
    publication: 1818,
    image: "src/images/books/frankestein.jpg",
    price: 1234,
  },
  {
    id: 12,
    title: "Soy Leyenda",
    genre: "Terror",
    author: "Richard Matheson",
    publication: 1954,
    image: "src/images/books/soy-leyenda.jpg",
    price: 1234,
  },
  {
    id: 13,
    title: "Un ángel No Debería Morir",
    genre: "Policial",
    author: "Jorge Zaragoza Gómez",
    publication: 2020,
    image: "src/images/books/un-angel-no-deberia-morir.jpg",
    price: 1234,
  },
  {
    id: 14,
    title: "Diez días para no morir",
    genre: "Policial",
    author: "Larenn, Luz",
    publication: 2023,
    image: "src/images/books/diez-dias-para-no-morir.jpg",
    price: 1234,
  },
  {
    id: 15,
    title: "La chica que se llevaron",
    genre: "Policial",
    author: "Donlea Charlie",
    publication: 2021,
    image: "src/images/books/la-chica-que-se-llevaron.jpg",
    price: 1234,
  },
  {
    id: 16,
    title: "Todos somos villanos",
    genre: "Policial",
    author: "Rio M.L",
    publication: 2023,
    image: "src/images/books/todos-somos-villanos.jpg",
    price: 1234,
  },
  {
    id: 17,
    title: "Silencios inconfesables",
    genre: "Policial",
    author: "Hjorth Michael",
    publication: 2023,
    image: "src/images/books/silencios-inconfesables.jpg",
    price: 1234,
  },
];
